server:
  port: ${PORT:0}

spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
  devtools:
    remote:
      restart:
        enabled: true
  application:
    name: user-ws
  boot:
    admin:
      client:
        url: http://localhost:8763
  cloud:
    config:
      url: http://localhost:8764

eureka:
  instance:
    instance-id: ${spring.application.name}.${spring.aplication.instance_id:${random.value}}
